version: '3.12'

services:
  web:
    build: .
    volumes:
      - .:/app
    image: mysite:v1
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    entrypoint: ["daphne", "-b", "0.0.0.0", "-p", "8080", "mysite.asgi:application"]

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
